[package]
name = "chronos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#logging
env_logger = "0.10.0"
log = { version = "0.4", features = [  "kv_unstable",    "std",    "kv_unstable_serde" ] }

#Exception handling
anyhow = "1.0.69"

#async
futures="0.3.26"
async-trait = "0.1.66"
tokio = { version = "1", features = ["full"] }

#data parsing
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"

# postgres = {version="0.19.4",features=["with-chrono-0_4","with-serde_json-1","with-uuid-1"]  }
tokio-postgres = {version="0.7.7", features=["with-chrono-0_4","with-serde_json-1","with-uuid-1"]  }
rdkafka = { version = "0.29.0" }
clap = { version = "4.1.4", features = ["derive"] }
chrono = "0.4.23"
uuid = { version="1.3.0", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }
dotenvy = "0.15"
clippy = "0.0.302"
hdrhistogram = "7.5.2"
deadpool-postgres = "0.10"
refinery = { version = "0.8.7", features = ["tokio-postgres"] }
thiserror = "1.0.31"
[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name="consumer_bench"
harness=false

