ARG RUST_VERSION=1.96.0
FROM rust:${RUST_VERSION}-bookworm AS build
# Install software
ENV CARGO_HTTP_CAINFO=/etc/ssl/certs/zscaler_cert.pem
COPY ./zscaler_cert.pem /etc/ssl/certs/zscaler_cert.pem
RUN update-ca-certificates && apt-get update && apt-get install -y libsasl2-dev
# Create appuser
ENV USER=chronos
ENV UID=1000
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

WORKDIR /tmp
# Build binary in release mode
COPY ./Cargo.lock \
    ./rust-toolchain.toml \
    ./Cargo.toml \
    ./

# Copy in pg_mig and examples so we don't break
# cargo builds (cargo will fail if it can't find pg_mig and examples)
# One per line so its cache optimized
COPY chronos_bin /tmp/chronos_bin
COPY pg_mig /tmp/pg_mig
COPY examples /tmp/examples

# Local caches to optimize the local build exp
RUN --mount=type=cache,target=/usr/local/cargo/registry/ \
    --mount=type=cache,target=/tmp/target/ \
    cargo build \
        -p chronos_bin \
        --release \
        --target-dir /build

#
# Run image based on bookworm-slim to reduce image size while still using glibc
#
FROM debian:bookworm-slim AS run
# SASL supports
ENV USER=chronos
ENV CARGO_HTTP_CAINFO=/etc/ssl/certs/zscaler_cert.pem
COPY ./zscaler_cert.pem /etc/ssl/certs/zscaler_cert.pem
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates && apt-get install -y libsasl2-dev
WORKDIR /opt/build
# Import users from build
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
# Copy binary from build
COPY --from=build /build/release/chronos /opt/build/chronos
# Use an unprivileged user
USER ${USER}:${USER}
# Entry point
CMD ["/opt/build/chronos"]
