[package]
name = "chronos_ex"
version = "0.0.2"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
dotenv = "0.15.0"
log = "0.4.14"

tokio = { version = "1.12.0", features = ["full"] }

chronos_bin={path="../../chronos_bin"}
